CREATE TABLE `prop_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '道具主键ID',
  `supplier_user_id` BIGINT NOT NULL COMMENT '所属工厂用户ID',
  `prop_name` VARCHAR(128) DEFAULT NULL COMMENT '道具名称，管理员预生成二维码时可暂为空',
  `image_url` VARCHAR(255) DEFAULT NULL COMMENT '道具图片地址',
  `style_code` VARCHAR(32) DEFAULT NULL COMMENT '风格编码，如 modern、traditional、tech',
  `type_code` VARCHAR(32) DEFAULT NULL COMMENT '类型编码，如 light、audio、screen、structure',
  `size_desc` VARCHAR(128) DEFAULT NULL COMMENT '尺寸补充描述，如异形、折叠后尺寸、展开后尺寸',
  `length_cm` DECIMAL(10,2) DEFAULT NULL COMMENT '长度，单位厘米',
  `width_cm` DECIMAL(10,2) DEFAULT NULL COMMENT '宽度，单位厘米',
  `height_cm` DECIMAL(10,2) DEFAULT NULL COMMENT '高度，单位厘米',
  `material_desc` VARCHAR(128) DEFAULT NULL COMMENT '材质说明',
  `daily_rent_price_fen` INT NOT NULL DEFAULT 0 COMMENT '日租金，单位分',
  `deposit_amount_fen` INT NOT NULL DEFAULT 0 COMMENT '押金金额，单位分',
  `fire_rating` VARCHAR(32) DEFAULT NULL COMMENT '防火等级',
  `transport_requirement` VARCHAR(255) DEFAULT NULL COMMENT '运输要求',
  `transport_suggestion` VARCHAR(128) DEFAULT NULL COMMENT '运输建议',
  `prop_status` VARCHAR(20) NOT NULL DEFAULT 'idle' COMMENT '道具状态：idle空闲 locked已锁定 renting租赁中 offline已下架',
  `audit_status` VARCHAR(20) NOT NULL DEFAULT 'approved' COMMENT '审核状态：pending待审核 approved通过 rejected驳回',
  `qr_code_id` VARCHAR(64) DEFAULT NULL COMMENT '二维码唯一标识',
  `qr_code_url` VARCHAR(255) DEFAULT NULL COMMENT '二维码图片地址',
  `fill_status` VARCHAR(20) NOT NULL DEFAULT 'filled' COMMENT '资料填写状态：pending_fill待补充 filled已补全',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注信息',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='道具信息表';

CREATE TABLE `rental_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '订单主键ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '业务订单编号',
  `project_id` BIGINT NOT NULL COMMENT '来源方案ID',
  `demander_user_id` BIGINT NOT NULL COMMENT '需求方用户ID',
  `supplier_user_id` BIGINT NOT NULL COMMENT '工厂方用户ID',
  `order_status` VARCHAR(32) NOT NULL COMMENT '订单状态：pending_factory_confirm待工厂确认 wait_pickup待取货 renting租赁中 wait_review待评价 completed已完成 cancelled_timeout超时取消 cancelled_manual人工取消',
  `rent_amount_fen` INT NOT NULL DEFAULT 0 COMMENT '租金总额，单位分',
  `deposit_amount_fen` INT NOT NULL DEFAULT 0 COMMENT '押金总额，单位分',
  `total_amount_fen` INT NOT NULL DEFAULT 0 COMMENT '订单应付总额，单位分',
  `pay_status` VARCHAR(20) NOT NULL DEFAULT 'unpaid' COMMENT '支付状态：unpaid未支付 paying支付中 paid已支付 closed已关闭 failed支付失败',
  `refund_status` VARCHAR(20) NOT NULL DEFAULT 'none' COMMENT '退款状态：none无退款 processing退款中 partial部分退款 full全额退款 failed退款失败',
  `current_payment_id` BIGINT DEFAULT NULL COMMENT '当前有效支付记录ID，关联 order_payment.id',
  `total_paid_fen` INT NOT NULL DEFAULT 0 COMMENT '累计已支付金额，单位分',
  `total_refunded_fen` INT NOT NULL DEFAULT 0 COMMENT '累计已退款金额，单位分',
  `confirm_deadline_at` DATETIME DEFAULT NULL COMMENT '工厂确认截止时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '订单创建时间',
  `paid_at` DATETIME DEFAULT NULL COMMENT '订单支付完成时间',
  `confirmed_at` DATETIME DEFAULT NULL COMMENT '工厂确认接单时间',
  `picked_up_at` DATETIME DEFAULT NULL COMMENT '全部出库完成时间',
  `returned_at` DATETIME DEFAULT NULL COMMENT '全部归还完成时间',
  `reviewed_at` DATETIME DEFAULT NULL COMMENT '用户评价完成时间',
  `cancelled_at` DATETIME DEFAULT NULL COMMENT '订单取消时间',
  `cancel_reason` VARCHAR(255) DEFAULT NULL COMMENT '订单取消原因',
  `deposit_refunded_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '押金是否已退回：0否 1是',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '订单备注',
  `created_by` BIGINT DEFAULT NULL COMMENT '订单创建人用户ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租赁订单主表';

CREATE TABLE `order_payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '支付记录主键ID',
  `payment_no` VARCHAR(64) NOT NULL COMMENT '系统内部支付流水号',
  `order_id` BIGINT NOT NULL COMMENT '关联业务订单ID',
  `pay_scene` VARCHAR(32) NOT NULL DEFAULT 'rent_deposit' COMMENT '支付场景：rent_deposit租金加押金 additional补差价 compensation赔付',
  `payment_channel` VARCHAR(32) NOT NULL DEFAULT 'wechat_miniapp' COMMENT '支付渠道：wechat_miniapp微信小程序支付',
  `payment_status` VARCHAR(32) NOT NULL DEFAULT 'created' COMMENT '支付状态：created已创建 paying支付中 success支付成功 fail支付失败 closed已关闭 refunded已退款 partial_refunded部分退款',
  `merchant_mchid` VARCHAR(32) NOT NULL COMMENT '微信支付商户号',
  `appid` VARCHAR(64) NOT NULL COMMENT '微信小程序APPID',
  `openid` VARCHAR(64) NOT NULL COMMENT '支付用户openid快照',
  `merchant_out_trade_no` VARCHAR(64) NOT NULL COMMENT '商户订单号，传给微信支付且必须唯一',
  `wx_transaction_id` VARCHAR(64) DEFAULT NULL COMMENT '微信支付订单号',
  `wx_prepay_id` VARCHAR(128) DEFAULT NULL COMMENT '微信预支付会话标识prepay_id',
  `description` VARCHAR(127) NOT NULL COMMENT '商品描述，对应微信支付下单description',
  `amount_fen` INT NOT NULL COMMENT '本次支付金额，单位分',
  `currency` VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种，默认人民币CNY',
  `client_ip` VARCHAR(64) DEFAULT NULL COMMENT '支付客户端IP',
  `notify_url` VARCHAR(255) DEFAULT NULL COMMENT '支付通知回调地址快照',
  `attach_data` VARCHAR(255) DEFAULT NULL COMMENT '附加透传数据',
  `time_expire` DATETIME DEFAULT NULL COMMENT '本次支付失效时间',
  `success_time` DATETIME DEFAULT NULL COMMENT '微信支付成功时间',
  `fail_reason` VARCHAR(255) DEFAULT NULL COMMENT '支付失败原因',
  `closed_reason` VARCHAR(255) DEFAULT NULL COMMENT '关单原因',
  `raw_create_response` JSON DEFAULT NULL COMMENT '统一下单原始响应报文',
  `raw_query_response` JSON DEFAULT NULL COMMENT '查单原始响应报文',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单支付交易表，一笔业务订单可对应多次支付尝试';

CREATE TABLE `payment_notify_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '支付通知日志主键ID',
  `notify_id` VARCHAR(64) NOT NULL COMMENT '微信支付通知唯一ID，用于幂等去重',
  `notify_type` VARCHAR(32) NOT NULL DEFAULT 'payment' COMMENT '通知类型：payment支付通知 refund退款通知',
  `event_type` VARCHAR(64) DEFAULT NULL COMMENT '微信通知事件类型',
  `resource_type` VARCHAR(64) DEFAULT NULL COMMENT '通知资源类型',
  `merchant_mchid` VARCHAR(32) DEFAULT NULL COMMENT '商户号',
  `appid` VARCHAR(64) DEFAULT NULL COMMENT '小程序APPID',
  `wechatpay_serial` VARCHAR(64) DEFAULT NULL COMMENT 'Wechatpay-Serial请求头值',
  `wechatpay_signature` VARCHAR(512) DEFAULT NULL COMMENT 'Wechatpay-Signature请求头值',
  `wechatpay_timestamp` VARCHAR(32) DEFAULT NULL COMMENT 'Wechatpay-Timestamp请求头值',
  `wechatpay_nonce` VARCHAR(64) DEFAULT NULL COMMENT 'Wechatpay-Nonce请求头值',
  `request_headers_json` JSON DEFAULT NULL COMMENT '回调请求头原始快照',
  `request_body` JSON NOT NULL COMMENT '回调请求体原始报文',
  `verify_status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '验签状态：pending待验签 success成功 fail失败',
  `decrypt_status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '解密状态：pending待解密 success成功 fail失败',
  `process_status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '业务处理状态：pending待处理 success成功 fail失败 ignored已忽略',
  `payment_no` VARCHAR(64) DEFAULT NULL COMMENT '关联支付流水号',
  `merchant_out_trade_no` VARCHAR(64) DEFAULT NULL COMMENT '关联商户订单号',
  `merchant_out_refund_no` VARCHAR(64) DEFAULT NULL COMMENT '关联商户退款单号',
  `wx_transaction_id` VARCHAR(64) DEFAULT NULL COMMENT '关联微信支付订单号',
  `wx_refund_id` VARCHAR(64) DEFAULT NULL COMMENT '关联微信退款单号',
  `summary` VARCHAR(255) DEFAULT NULL COMMENT '处理摘要信息',
  `error_message` VARCHAR(500) DEFAULT NULL COMMENT '验签、解密或业务处理失败原因',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '通知接收时间',
  `processed_at` DATETIME DEFAULT NULL COMMENT '通知处理完成时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信支付异步通知日志表，用于验签、解密、幂等和审计';

CREATE TABLE `order_refund` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '退款记录主键ID',
  `refund_no` VARCHAR(64) NOT NULL COMMENT '系统内部退款流水号',
  `order_id` BIGINT NOT NULL COMMENT '关联业务订单ID',
  `payment_id` BIGINT NOT NULL COMMENT '关联支付记录ID',
  `refund_scene` VARCHAR(32) NOT NULL COMMENT '退款场景：deposit押金退款 timeout_cancel超时取消退款 dispute纠纷退款 manual人工退款',
  `refund_status` VARCHAR(32) NOT NULL DEFAULT 'created' COMMENT '退款状态：created已创建 processing退款中 success退款成功 fail退款失败 closed已关闭 abnormal异常',
  `merchant_mchid` VARCHAR(32) NOT NULL COMMENT '微信支付商户号',
  `appid` VARCHAR(64) NOT NULL COMMENT '微信小程序APPID',
  `merchant_out_refund_no` VARCHAR(64) NOT NULL COMMENT '商户退款单号，调用微信退款接口时必须唯一',
  `wx_refund_id` VARCHAR(64) DEFAULT NULL COMMENT '微信退款单号',
  `merchant_out_trade_no` VARCHAR(64) NOT NULL COMMENT '原支付商户订单号',
  `wx_transaction_id` VARCHAR(64) DEFAULT NULL COMMENT '原微信支付订单号',
  `total_amount_fen` INT NOT NULL COMMENT '原支付总金额，单位分',
  `refund_amount_fen` INT NOT NULL COMMENT '本次退款金额，单位分',
  `currency` VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种，默认人民币CNY',
  `reason` VARCHAR(255) DEFAULT NULL COMMENT '退款原因',
  `notify_url` VARCHAR(255) DEFAULT NULL COMMENT '退款结果通知地址快照',
  `success_time` DATETIME DEFAULT NULL COMMENT '退款成功时间',
  `fail_reason` VARCHAR(255) DEFAULT NULL COMMENT '退款失败原因',
  `raw_refund_response` JSON DEFAULT NULL COMMENT '微信退款接口原始响应报文',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单退款记录表，一笔支付可对应多次退款';
