CREATE TABLE `sys_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(64) NOT NULL,
  `avatar_url` VARCHAR(255) DEFAULT NULL,
  `phone` VARCHAR(20) DEFAULT NULL,
  `realname_verified` TINYINT NOT NULL DEFAULT 0,
  `student_verified` TINYINT NOT NULL DEFAULT 0,
  `credit_score` INT NOT NULL DEFAULT 80,
  `user_status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `register_status` VARCHAR(32) NOT NULL DEFAULT 'new',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_sys_user_phone` (`phone`),
  KEY `idx_sys_user_register_status` (`register_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `sys_user_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `role_code` VARCHAR(20) NOT NULL,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_role` (`user_id`, `role_code`),
  KEY `idx_sys_user_role_role` (`role_code`, `enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `sys_user_wechat` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `openid` VARCHAR(64) NOT NULL,
  `unionid` VARCHAR(64) DEFAULT NULL,
  `session_key` VARCHAR(128) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_wechat_openid` (`openid`),
  UNIQUE KEY `uk_sys_user_wechat_user_id` (`user_id`),
  KEY `idx_sys_user_wechat_unionid` (`unionid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `factory_invite_code` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code_hash` VARCHAR(128) NOT NULL,
  `plain_code` VARCHAR(64) DEFAULT NULL,
  `code_suffix` VARCHAR(16) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'unused',
  `expire_at` DATETIME NOT NULL,
  `created_by_admin_user_id` BIGINT NOT NULL,
  `locked_by_user_id` BIGINT DEFAULT NULL,
  `locked_at` DATETIME DEFAULT NULL,
  `used_by_user_id` BIGINT DEFAULT NULL,
  `used_at` DATETIME DEFAULT NULL,
  `revoked_by_admin_user_id` BIGINT DEFAULT NULL,
  `revoked_at` DATETIME DEFAULT NULL,
  `remark` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_factory_invite_code_hash` (`code_hash`),
  KEY `idx_factory_invite_code_status` (`status`),
  KEY `idx_factory_invite_code_suffix` (`code_suffix`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `factory_profile` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `owner_user_id` BIGINT NOT NULL,
  `factory_name` VARCHAR(128) NOT NULL,
  `unified_social_credit_code` VARCHAR(32) NOT NULL,
  `business_license_url` VARCHAR(255) NOT NULL,
  `contact_name` VARCHAR(64) NOT NULL,
  `contact_phone` VARCHAR(20) NOT NULL,
  `factory_address` VARCHAR(255) NOT NULL,
  `main_business` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `approved_audit_id` BIGINT DEFAULT NULL,
  `approved_by_admin_user_id` BIGINT DEFAULT NULL,
  `approved_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_factory_profile_owner` (`owner_user_id`),
  UNIQUE KEY `uk_factory_profile_credit_code` (`unified_social_credit_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `supplier_settlement_audit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `applicant_user_id` BIGINT DEFAULT NULL,
  `invite_code_id` BIGINT DEFAULT NULL,
  `company_name` VARCHAR(128) NOT NULL,
  `factory_name` VARCHAR(128) DEFAULT NULL,
  `unified_social_credit_code` VARCHAR(32) DEFAULT NULL,
  `business_license_url` VARCHAR(255) DEFAULT NULL,
  `contact_name` VARCHAR(64) NOT NULL,
  `contact_phone` VARCHAR(20) NOT NULL,
  `factory_address` VARCHAR(255) DEFAULT NULL,
  `main_business` VARCHAR(255) DEFAULT NULL,
  `remark` VARCHAR(255) DEFAULT NULL,
  `audit_status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `audit_remark` VARCHAR(255) DEFAULT NULL,
  `reject_reason` VARCHAR(255) DEFAULT NULL,
  `reviewer_id` BIGINT DEFAULT NULL,
  `reviewed_by_admin_user_id` BIGINT DEFAULT NULL,
  `submitted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reviewed_at` DATETIME DEFAULT NULL,
  `created_factory_id` BIGINT DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_factory_audit_status` (`audit_status`, `submitted_at`),
  KEY `idx_factory_audit_applicant` (`applicant_user_id`, `audit_status`),
  KEY `idx_factory_audit_invite` (`invite_code_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `prop_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `supplier_user_id` BIGINT DEFAULT NULL,
  `prop_name` VARCHAR(128) DEFAULT NULL,
  `image_url` VARCHAR(512) DEFAULT NULL,
  `style_code` VARCHAR(32) DEFAULT NULL,
  `type_code` VARCHAR(32) DEFAULT NULL,
  `size_desc` VARCHAR(128) DEFAULT NULL,
  `length_cm` DECIMAL(10,2) DEFAULT NULL,
  `width_cm` DECIMAL(10,2) DEFAULT NULL,
  `height_cm` DECIMAL(10,2) DEFAULT NULL,
  `material_desc` VARCHAR(128) DEFAULT NULL,
  `daily_rent_price_fen` INT NOT NULL DEFAULT 0,
  `deposit_amount_fen` INT NOT NULL DEFAULT 0,
  `fire_resistant_option` VARCHAR(32) DEFAULT NULL,
  `weight_desc` VARCHAR(64) DEFAULT NULL,
  `transport_suggestion` VARCHAR(255) DEFAULT NULL,
  `prop_status` VARCHAR(20) NOT NULL DEFAULT 'idle',
  `audit_status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `qr_code_id` VARCHAR(64) DEFAULT NULL,
  `qr_code_url` VARCHAR(512) DEFAULT NULL,
  `fill_status` VARCHAR(20) NOT NULL DEFAULT 'filled',
  `remark` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_prop_qr_code_id` (`qr_code_id`),
  KEY `idx_prop_supplier_status` (`supplier_user_id`, `prop_status`),
  KEY `idx_prop_style_type_status` (`style_code`, `type_code`, `prop_status`),
  KEY `idx_prop_fill_audit_status` (`fill_status`, `audit_status`, `prop_status`),
  KEY `idx_prop_price` (`daily_rent_price_fen`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `prop_image` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `prop_id` BIGINT NOT NULL,
  `image_url` VARCHAR(512) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_prop_image_prop` (`prop_id`, `sort_order`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `prop_qr_code` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `prop_id` BIGINT NOT NULL,
  `qr_code_id` VARCHAR(64) NOT NULL,
  `qr_scene` VARCHAR(128) NOT NULL,
  `qr_page` VARCHAR(128) NOT NULL,
  `qr_image_url` VARCHAR(512) DEFAULT NULL,
  `qr_image_storage_key` VARCHAR(512) DEFAULT NULL,
  `image_sha256` VARCHAR(64) DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'unused',
  `printed_flag` TINYINT NOT NULL DEFAULT 0,
  `printed_at` DATETIME DEFAULT NULL,
  `downloaded_at` DATETIME DEFAULT NULL,
  `created_by_admin_user_id` BIGINT DEFAULT NULL,
  `used_by_supplier_user_id` BIGINT DEFAULT NULL,
  `used_at` DATETIME DEFAULT NULL,
  `revoked_by_admin_user_id` BIGINT DEFAULT NULL,
  `revoked_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_prop_qr_code_id` (`qr_code_id`),
  UNIQUE KEY `uk_prop_qr_prop_id` (`prop_id`),
  KEY `idx_prop_qr_status` (`status`),
  KEY `idx_prop_qr_created_admin` (`created_by_admin_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `prop_audit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `prop_id` BIGINT NOT NULL,
  `action_type` VARCHAR(20) NOT NULL,
  `audit_status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `apply_remark` VARCHAR(255) DEFAULT NULL,
  `audit_remark` VARCHAR(255) DEFAULT NULL,
  `reviewer_id` BIGINT DEFAULT NULL,
  `submitted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reviewed_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_prop_audit_status` (`audit_status`, `submitted_at`),
  KEY `idx_prop_audit_prop` (`prop_id`, `audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `project_scheme` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `project_name` VARCHAR(128) NOT NULL,
  `project_description` VARCHAR(500) DEFAULT NULL,
  `project_status` VARCHAR(20) NOT NULL DEFAULT 'editing',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ordered_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_project_user_status` (`user_id`, `project_status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `project_scheme_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `prop_id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_project_prop` (`project_id`, `prop_id`),
  KEY `idx_project_item_prop` (`prop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `rental_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(64) NOT NULL,
  `project_id` BIGINT NOT NULL,
  `demander_user_id` BIGINT NOT NULL,
  `supplier_user_id` BIGINT NOT NULL,
  `order_status` VARCHAR(32) NOT NULL,
  `rental_days` INT NOT NULL DEFAULT 1,
  `rental_start_date` DATE DEFAULT NULL,
  `rental_end_date` DATE DEFAULT NULL,
  `contact_address` VARCHAR(255) DEFAULT NULL,
  `use_scene` VARCHAR(255) DEFAULT NULL,
  `special_remark` VARCHAR(500) DEFAULT NULL,
  `rent_amount_fen` INT NOT NULL DEFAULT 0,
  `deposit_amount_fen` INT NOT NULL DEFAULT 0,
  `total_amount_fen` INT NOT NULL DEFAULT 0,
  `pay_status` VARCHAR(20) NOT NULL DEFAULT 'unpaid',
  `refund_status` VARCHAR(20) NOT NULL DEFAULT 'none',
  `current_payment_id` BIGINT DEFAULT NULL,
  `total_paid_fen` INT NOT NULL DEFAULT 0,
  `total_refunded_fen` INT NOT NULL DEFAULT 0,
  `confirm_deadline_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `paid_at` DATETIME DEFAULT NULL,
  `confirmed_at` DATETIME DEFAULT NULL,
  `picked_up_at` DATETIME DEFAULT NULL,
  `returned_at` DATETIME DEFAULT NULL,
  `reviewed_at` DATETIME DEFAULT NULL,
  `cancelled_at` DATETIME DEFAULT NULL,
  `cancel_reason` VARCHAR(255) DEFAULT NULL,
  `deposit_refunded_flag` TINYINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(255) DEFAULT NULL,
  `created_by` BIGINT DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rental_order_no` (`order_no`),
  KEY `idx_rental_order_demander` (`demander_user_id`, `created_at`),
  KEY `idx_rental_order_supplier_status` (`supplier_user_id`, `order_status`, `created_at`),
  KEY `idx_rental_order_status_deadline` (`order_status`, `confirm_deadline_at`),
  KEY `idx_rental_order_wait_review_returned` (`order_status`, `returned_at`),
  KEY `idx_rental_order_project_id` (`project_id`),
  KEY `idx_rental_order_current_payment_id` (`current_payment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `rental_order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL,
  `prop_id` BIGINT NOT NULL,
  `prop_name_snapshot` VARCHAR(128) NOT NULL,
  `image_url_snapshot` VARCHAR(512) DEFAULT NULL,
  `daily_rent_price_fen_snapshot` INT NOT NULL DEFAULT 0,
  `deposit_amount_fen_snapshot` INT NOT NULL DEFAULT 0,
  `outbound_status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `return_status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `outbound_scanned_at` DATETIME DEFAULT NULL,
  `return_scanned_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_prop` (`order_id`, `prop_id`),
  KEY `idx_order_item_prop` (`prop_id`, `return_status`),
  KEY `idx_order_item_outbound` (`order_id`, `outbound_status`),
  KEY `idx_order_item_return` (`order_id`, `return_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_scan_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL,
  `order_item_id` BIGINT DEFAULT NULL,
  `prop_id` BIGINT DEFAULT NULL,
  `qr_code_id` VARCHAR(64) DEFAULT NULL,
  `scan_type` VARCHAR(20) NOT NULL,
  `scan_status` VARCHAR(20) NOT NULL DEFAULT 'success',
  `scan_user_id` BIGINT NOT NULL,
  `supplier_user_id` BIGINT DEFAULT NULL,
  `raw_scan_result` VARCHAR(1000) DEFAULT NULL,
  `fail_reason` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_order_scan_log_order_type` (`order_id`, `scan_type`, `created_at`),
  KEY `idx_order_scan_log_prop` (`prop_id`, `scan_type`, `created_at`),
  KEY `idx_order_scan_log_user` (`scan_user_id`, `created_at`),
  KEY `idx_order_scan_log_qr_code` (`qr_code_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `payment_no` VARCHAR(64) NOT NULL,
  `order_id` BIGINT NOT NULL,
  `pay_scene` VARCHAR(32) NOT NULL DEFAULT 'rent_deposit',
  `payment_channel` VARCHAR(32) NOT NULL DEFAULT 'wechat_miniapp',
  `payment_status` VARCHAR(32) NOT NULL DEFAULT 'created',
  `merchant_mchid` VARCHAR(32) NOT NULL,
  `appid` VARCHAR(64) NOT NULL,
  `openid` VARCHAR(64) NOT NULL,
  `merchant_out_trade_no` VARCHAR(64) NOT NULL,
  `wx_transaction_id` VARCHAR(64) DEFAULT NULL,
  `wx_prepay_id` VARCHAR(128) DEFAULT NULL,
  `description` VARCHAR(127) NOT NULL,
  `amount_fen` INT NOT NULL,
  `currency` VARCHAR(8) NOT NULL DEFAULT 'CNY',
  `client_ip` VARCHAR(64) DEFAULT NULL,
  `notify_url` VARCHAR(255) DEFAULT NULL,
  `attach_data` VARCHAR(255) DEFAULT NULL,
  `time_expire` DATETIME DEFAULT NULL,
  `success_time` DATETIME DEFAULT NULL,
  `fail_reason` VARCHAR(255) DEFAULT NULL,
  `closed_reason` VARCHAR(255) DEFAULT NULL,
  `raw_create_response` JSON DEFAULT NULL,
  `raw_query_response` JSON DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_payment_no` (`payment_no`),
  UNIQUE KEY `uk_order_payment_out_trade_no` (`merchant_out_trade_no`),
  KEY `idx_order_payment_order_id` (`order_id`),
  KEY `idx_order_payment_status` (`payment_status`),
  KEY `idx_order_payment_wx_transaction_id` (`wx_transaction_id`),
  KEY `idx_order_payment_openid` (`openid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `payment_notify_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `notify_id` VARCHAR(64) NOT NULL,
  `notify_type` VARCHAR(32) NOT NULL DEFAULT 'payment',
  `event_type` VARCHAR(64) DEFAULT NULL,
  `resource_type` VARCHAR(64) DEFAULT NULL,
  `merchant_mchid` VARCHAR(32) DEFAULT NULL,
  `appid` VARCHAR(64) DEFAULT NULL,
  `wechatpay_serial` VARCHAR(64) DEFAULT NULL,
  `wechatpay_signature` VARCHAR(512) DEFAULT NULL,
  `wechatpay_timestamp` VARCHAR(32) DEFAULT NULL,
  `wechatpay_nonce` VARCHAR(64) DEFAULT NULL,
  `request_headers_json` JSON DEFAULT NULL,
  `request_body` JSON NOT NULL,
  `verify_status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `decrypt_status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `process_status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `payment_no` VARCHAR(64) DEFAULT NULL,
  `merchant_out_trade_no` VARCHAR(64) DEFAULT NULL,
  `merchant_out_refund_no` VARCHAR(64) DEFAULT NULL,
  `wx_transaction_id` VARCHAR(64) DEFAULT NULL,
  `wx_refund_id` VARCHAR(64) DEFAULT NULL,
  `summary` VARCHAR(255) DEFAULT NULL,
  `error_message` VARCHAR(500) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `processed_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_notify_id` (`notify_id`),
  KEY `idx_payment_notify_process_status` (`process_status`),
  KEY `idx_payment_notify_out_trade_no` (`merchant_out_trade_no`),
  KEY `idx_payment_notify_out_refund_no` (`merchant_out_refund_no`),
  KEY `idx_payment_notify_payment_no` (`payment_no`),
  KEY `idx_payment_notify_wx_transaction_id` (`wx_transaction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_refund` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `refund_no` VARCHAR(64) NOT NULL,
  `order_id` BIGINT NOT NULL,
  `payment_id` BIGINT NOT NULL,
  `refund_scene` VARCHAR(32) NOT NULL,
  `refund_status` VARCHAR(32) NOT NULL DEFAULT 'created',
  `merchant_mchid` VARCHAR(32) NOT NULL,
  `appid` VARCHAR(64) NOT NULL,
  `merchant_out_refund_no` VARCHAR(64) NOT NULL,
  `wx_refund_id` VARCHAR(64) DEFAULT NULL,
  `merchant_out_trade_no` VARCHAR(64) NOT NULL,
  `wx_transaction_id` VARCHAR(64) DEFAULT NULL,
  `total_amount_fen` INT NOT NULL,
  `refund_amount_fen` INT NOT NULL,
  `currency` VARCHAR(8) NOT NULL DEFAULT 'CNY',
  `reason` VARCHAR(255) DEFAULT NULL,
  `notify_url` VARCHAR(255) DEFAULT NULL,
  `success_time` DATETIME DEFAULT NULL,
  `fail_reason` VARCHAR(255) DEFAULT NULL,
  `raw_refund_response` JSON DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_refund_no` (`refund_no`),
  UNIQUE KEY `uk_order_refund_out_refund_no` (`merchant_out_refund_no`),
  KEY `idx_order_refund_order_id` (`order_id`),
  KEY `idx_order_refund_payment_id` (`payment_id`),
  KEY `idx_order_refund_status` (`refund_status`),
  KEY `idx_order_refund_wx_refund_id` (`wx_refund_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_review` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL,
  `reviewer_user_id` BIGINT NOT NULL,
  `reviewer_role` VARCHAR(20) NOT NULL,
  `score` INT NOT NULL,
  `prop_score` INT NOT NULL DEFAULT 5,
  `counterparty_score` INT NOT NULL DEFAULT 5,
  `content` VARCHAR(1000) DEFAULT NULL,
  `visible_flag` TINYINT NOT NULL DEFAULT 1,
  `auto_flag` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_reviewer_role` (`order_id`, `reviewer_role`),
  KEY `idx_order_review_visible` (`visible_flag`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_dispute` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NOT NULL,
  `apply_user_id` BIGINT NOT NULL,
  `applicant_role` VARCHAR(20) NOT NULL DEFAULT 'demander',
  `apply_stage` VARCHAR(32) NOT NULL DEFAULT 'unknown',
  `title` VARCHAR(128) NOT NULL,
  `content` VARCHAR(2000) NOT NULL,
  `claim_amount_fen` INT NOT NULL DEFAULT 0,
  `deposit_amount_fen_snapshot` INT NOT NULL DEFAULT 0,
  `order_status_snapshot` VARCHAR(32) DEFAULT NULL,
  `demander_user_id` BIGINT DEFAULT NULL,
  `supplier_user_id` BIGINT DEFAULT NULL,
  `evidence_urls` VARCHAR(2000) DEFAULT NULL,
  `dispute_status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `resolution` VARCHAR(2000) DEFAULT NULL,
  `resolution_type` VARCHAR(20) DEFAULT NULL,
  `refund_status` VARCHAR(32) NOT NULL DEFAULT 'none',
  `reviewer_id` BIGINT DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `resolved_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_order_dispute_order_status` (`order_id`, `dispute_status`),
  KEY `idx_order_dispute_applicant` (`apply_user_id`, `applicant_role`, `dispute_status`),
  KEY `idx_order_dispute_participant_status` (`demander_user_id`, `supplier_user_id`, `dispute_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `user_credit_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `change_type` VARCHAR(32) NOT NULL,
  `biz_type` VARCHAR(32) DEFAULT NULL,
  `biz_id` BIGINT DEFAULT NULL,
  `before_score` INT NOT NULL,
  `delta_score` INT NOT NULL,
  `after_score` INT NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `operator_user_id` BIGINT DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_credit_log_user_time` (`user_id`, `created_at`),
  KEY `idx_credit_log_biz` (`biz_type`, `biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
