CREATE TABLE `order_fund_flow` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `flow_no` VARCHAR(64) NOT NULL,
  `order_id` BIGINT NOT NULL,
  `dispute_id` BIGINT DEFAULT NULL,
  `payment_id` BIGINT DEFAULT NULL,
  `flow_type` VARCHAR(40) NOT NULL,
  `flow_direction` VARCHAR(40) NOT NULL,
  `payer_role` VARCHAR(32) NOT NULL DEFAULT 'platform',
  `payer_user_id` BIGINT DEFAULT NULL,
  `receiver_role` VARCHAR(32) NOT NULL,
  `receiver_user_id` BIGINT DEFAULT NULL,
  `amount_fen` INT NOT NULL,
  `currency` VARCHAR(8) NOT NULL DEFAULT 'CNY',
  `channel_action` VARCHAR(40) NOT NULL,
  `channel_status` VARCHAR(32) NOT NULL DEFAULT 'created',
  `wechat_out_no` VARCHAR(64) DEFAULT NULL,
  `wechat_transaction_id` VARCHAR(64) DEFAULT NULL,
  `wechat_response` JSON DEFAULT NULL,
  `remark` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_fund_flow_no` (`flow_no`),
  KEY `idx_order_fund_flow_order` (`order_id`, `flow_type`),
  KEY `idx_order_fund_flow_dispute` (`dispute_id`),
  KEY `idx_order_fund_flow_receiver` (`receiver_role`, `receiver_user_id`),
  KEY `idx_order_fund_flow_status` (`channel_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
